Add unit test for `apply_ap_tracking_correction` with invalid offset
lambdaclass/cleopatra_cairo pull request #1661
Opened 2024-03-13 14:11 UTC by tcoratger

# Add unit test for `apply_ap_tracking_correction` with invalid offset

## Description

This pull request adds a new unit test for the `apply_ap_tracking_correction` function in order to cover the scenario where the offset of the hint AP tracking is invalid. This ensures better test coverage and helps identify potential issues related to AP tracking correction.

## Checklist
- [ ] Linked to Github Issue
- [X] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

2024-04-16 17:06 UTC, Oppen approved these changes

2024-05-09 10:52 UTC, Oppen commented on vm/src/hint_processor/builtin_hint_processor/garaga.rs
> +pub fn get_felt_bitlength(
Hi @tcoratger. Because this method is public, you'll need to update the changelog, as the rename is a breaking change.

2024-05-09 10:53 UTC, Oppen requested changes
Need a changelog entry pointing out the breaking change.

2026-01-26 14:59 UTC, gabrielbosio commented
`tracking_correction_invalid_group` already addresses this. This test should check for an invalid offset in the same hint group.

2026-02-10 20:19 UTC, closed without merging

2026-02-10 20:19 UTC, gabrielbosio commented
superseded by #2327