[HINTS] Add implementation of cairo_keccak/keccak hints
lambdaclass/cleopatra_cairo pull request #351
Opened 2022-08-04 22:16 UTC by entropidelic

# TITLE

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2022-08-06 16:38 UTC, Oppen requested changes

2022-08-06 16:38 UTC, Oppen commented on src/vm/hints/cairo_keccak/keccak_hints.rs
> +    }
If these are compile time constants there's no point in checking they're in range.

2022-08-06 16:38 UTC, Oppen commented on src/vm/hints/cairo_keccak/keccak_hints.rs
> +    padding.extend(u64_array_to_bigint_vec(&inp));
```suggestion
    let mut padding = [bigint!(0); KECCAK_STATE_SIZE_FELTS + KECCAK_STATE_SIZE_FELTS];
    keccak::f1600(&mut padding[KECCAK_STATE_SIZE_FELT .. ]);
```
NOTE: `keccak:f1600` will need to receive a mutable slice of `BigInt`.

2022-08-06 16:38 UTC, Oppen commented on src/vm/hints/cairo_keccak/keccak_hints.rs
> +    }
```suggestion
    for _ in 0..(BLOCK_SIZE - 1) {
        padding.extend_from_slice(padding.as_slice());
    }
```

2022-08-06 16:38 UTC, Oppen commented on src/vm/hints/cairo_keccak/keccak_hints.rs
> +    }
The first clone may still be needed, but the second part applies and avoids cloning in a loop.

2022-08-06 16:38 UTC, Oppen commented on src/vm/hints/cairo_keccak/keccak_hints.rs
> +                Err(VirtualMachineError::NoneInMemoryRange)
`ExpectedInt` would be a better error. Otherwise, a `Relocatable` would give us a misleading error.

2022-08-06 16:38 UTC, Oppen commented on src/vm/hints/cairo_keccak/keccak_hints.rs
> +        .write_arg(&mut vm.memory, &keccak_ptr, &bigint_values, Some(&vm.prime))
Is there any chance to pass `bigint_values` as an iterator instead? This would save us from actually creating the vector.

2022-08-08 20:11 UTC, pefontana approved these changes

2022-08-08 20:11 UTC, merged